<?php
// Including the necessary files and establishing a connection to the database.
include 'functions.php';
// Define API key from environment variable.
$api_key = getenv("API_KEY");

// Check the connection and die with a message if there's an error.
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// Initialize variables to hold the output and similar recipes.
$output = "";
$similarRecipes = "";

// Check if the request method is GET and if the query parameter is set.
if ($_SERVER["REQUEST_METHOD"] === "GET" && isset($_GET["query"])) {
    $query = $_GET["query"];
 

    // Try fetching the recipe from the database.
    $result = getRecipeFromDB($conn, $query);
    
  
    if ($result !== null) {
        $recipe = $result['output'];
        // Check if 'similar_recipes' index is set in $result
        if (isset($result['similarRecipes']) && !empty($result['similarRecipes']) && $result['similarRecipes'] !== null && $result['similarRecipes'] !== "") {
            $similarRecipes = renderSimilarRecipes($result['similarRecipes']);
        }
        $output .= $recipe;
    }else {
            // Fetch the recipe using the API if not found in the database.
            $response_data = fetchRecipeFromAPI($query);
            // If an error is returned from the API, die with a message.
            if (isset($response_data['error'])) {
                die($response_data['error']);
            }

            // Process the generated recipe and die with a message if there's an error.
            $recipe_parts = processGeneratedRecipe($response_data);
            //print a message saying that the recipe is not found
            //print_r($recipe_parts);
        
            if (isset($recipe_parts['error'])) {
                die($recipe_parts['error']);
            }

            // Process the individual components of the recipe.
            $name = processName($recipe_parts['name']);
            $ingredients = processIngredients($recipe_parts['ingredients']);
            $instructions = processInstructions($recipe_parts['instructions']);
            $story = processStory($recipe_parts['story'], $query, $api_key); // Handle case when story is an empty string
            $similarRecipesArray = $recipe_parts['similar_recipes'];
           
            

            // Prepare and save the recipe to the database.
            prepareAndSaveRecipe($conn, $name, $ingredients, $instructions, $story, $similarRecipesArray);
            
            $similarRecipes = renderSimilarRecipes($similarRecipesArray);
            
            // Fetch, process, and save the image and update the database with the image URL.
            $image_file_name = "images/" . preg_replace("/[^a-zA-Z0-9]/", "", $name) . ".png";
            $imageResponse = fetchImageFromAPI($name, $story, $api_key);
            $imageResponseProcessed = processImageResponse($imageResponse);

            if (isset($imageResponseProcessed['error'])) die($imageResponseProcessed['error']);
            
            $imageDataProcessed = getImageData($imageResponseProcessed['image_url']);
            if (isset($imageDataProcessed['error'])) die($imageDataProcessed['error']);

            $imageSaved = saveImageData($imageDataProcessed['image_data'], $image_file_name);
            if (isset($imageSaved['error'])) die($imageSaved['error']);

            // Update the database with the image URL.
            updateRecipeImageURL($conn, $image_file_name, $name);

            // Render the recipe and append it to the output.
            $output .= renderRecipe($name, $ingredients, $instructions, $story, $image_file_name);
        }
}

// Close the database connection.
$conn->close();
// Load the HTML content, replace the placeholders with the actual content, and echo the final content.
$html_content = file_get_contents("display.html");
$final_content = str_replace("<!--RECIPE_RESULTS-->", $output, $html_content);//here $output is the recipe that is found in the database or generated by the API and we are replacing the placeholder with the recipe
$final_content = str_replace("<!--SIMILAR_RECIPES-->", $similarRecipes, $final_content);
echo $final_content;
